server:
  port: 666

spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/cs_cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      routes:
#        - id: greet_hello
#          uri: http://127.0.0.1:7100/greet
#          predicates:
#          - Path=/hello/**
#        - id: greet_hi
#          uri: http://127.0.0.1:7200/greet
#          predicates:
#          - Path=/hi/**