server:
  port: 7007

spring:
  application:
    name: ZUUL-PROXY
  datasource:
    url: jdbc:h2:file:./.h2/zuul
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7000/eureka

zuul:
  routes:
    all:
      path: /api/**
      url: http://localhost:7007

ribbon:
  eager-load:
    enabled: true
    clients: service_hello
  eureka:
    enabled: false