
server:
  port: 7000

spring:
  application:
    name: EUREKA_SERVER

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.5
    # 自我保护机制
    enable-self-preservation: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka