server:
  port: 7008
spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/cs_sys?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver